---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: flux-vault-demo
  namespace: default
spec:
  provider: vault
  parameters:
    roleName: flux-vault-demo # Vault role defined in 'kubernetes' backend
    vaultAddress: http://vault.vault.svc.cluster.local:8200
    objects: |
      - objectName: demoPassword
        secretPath: demo/data/creds
        secretKey: password
