---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tf-controller
      version: 0.3.9
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      interval: 1m
  values:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
