---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: azure-config
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is a sample set of objects for Azure such as role bindings.
spec:
  interval: 10m