apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8200
    hostPort: 8200
    protocol: TCP
  # - containerPort: 443
  #   hostPort: 30443
  #   protocol: TCP
  # extraMounts:
  # - hostPath: /var/run/docker.sock
  #   containerPath: /var/run/docker.sock