---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: csi-driver
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/csi-driver
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: csi-driver
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/vault
  prune: true
  validation: client
