---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      # version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
      interval: 1m
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true
