apiVersion: templates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: azure-function
  namespace: flux-system
  labels:
    weave.works/template-type: terraform
spec:
  description: This is a template to create a simple Azure Function in EU regions
  renderType: templating
  params:
    - name: CLUSTER_NAME
      description: This is used for the cluster naming.
  resourcetemplates:
    - apiVersion: cluster.x-k8s.io/v1alpha3
      kind: Cluster
      metadata:
      name: "{{ .params.CLUSTER_NAME }}"
        