apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000 # vault ui
    hostPort: 8200
    protocol: TCP
  - containerPort: 31000 # injector demo
    hostPort: 9000
    protocol: TCP
  - containerPort: 31001 # csi demo
    hostPort: 9001
    protocol: TCP
