---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-vault-demo-injector
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-vault-demo-injector
  namespace: default
  labels:
    app: flux-vault-demo-injector
spec:
  selector:
    matchLabels:
      app: flux-vault-demo-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: flux-vault-demo-injector
      annotations:
        vault.hashicorp.com/agent-inject: 'true' # Really important!!!
        vault.hashicorp.com/role: flux-vault-demo
        vault.hashicorp.com/template-static-secret-render-interval: 10s # Default 5m - only applies to static secrets (ie kv or kv-v2)
        # vault.hashicorp.com/agent-inject-default-template: json
        vault.hashicorp.com/agent-inject-secret-file-creds: demo/creds
        vault.hashicorp.com/agent-inject-template-file-creds: |
          {{- with secret "demo/creds" -}}
          username={{ .Data.data.username }}
          password={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-env-creds: demo/creds
        vault.hashicorp.com/agent-inject-template-env-creds: |
          {{- with secret "demo/creds" -}}
          export DEMO_USERNAME={{ .Data.data.username }}
          export DEMO_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: flux-vault-demo-injector
      containers:
        - name: flux-vault-demo
          image: ghcr.io/rparmer/flux-vault-demo:latest
          imagePullPolicy: Always
          command: ['/bin/sh']
          args: ['-c', 'source /vault/secrets/env-creds && /demo/app'] # inject as env vars
          env:
            - name: CREDS_FILE
              value: /vault/secrets/file-creds # inject as file
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flux-vault-demo-injector
  namespace: default
spec:
  type: NodePort
  selector:
    app: flux-vault-demo-injector
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 31000
