---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/apps
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: terraform
  namespace: flux-system
  annotations:
    metadata.weave.works/description: "This sets up the tf-controller via a helm release"
spec:
  interval: 10m0s
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/terraform
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: terraform
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./demo
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: terraform
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./wego
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-notification
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./notifications
  prune: true
  validation: client
